using System.Text;
using System.Xml;
using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using MangaMagnet.Core.CBZ.ComicInfo.XML;
using Microsoft.Extensions.Logging;

namespace MangaMagnet.Core.CBZ.ComicInfo;

public class ComicInfoService(ILogger<ComicInfoService> logger)
{
	private readonly IExtendedXmlSerializer _serializer = new ConfigurationContainer()
		.Emit(EmitBehaviors.WhenModified)
		.EnableParameterizedContentWithPropertyAssignments()
		.UseOptimizedNamespaces()
		.Create();

	public XmlComicInfo Create(ComicInfoInput input)
	{
		var (pagePaths, (scanlationGroup, chapterTitle, chapterNumber, volumeNumber, uploadedAt), mangaMetadata, version) = input;

		var pages = pagePaths
			.Select(path => new FileInfo(path))
			.Select(file => new PageInfo { Image = int.Parse(file.Name.Split(".").First()), ImageSize = file.Length, })
			.ToList();

		var comicInfo = new ComicInfo
		{
			Title = chapterTitle,
			Series = mangaMetadata.DisplayTitle,
			AlternateSeries = string.Join(",", mangaMetadata.Aliases),
			Number = chapterNumber.ToString(),
			Volume = volumeNumber,
			Summary = mangaMetadata.Description,
			Year = uploadedAt?.Year,
			Month = uploadedAt?.Month,
			Day = uploadedAt?.Day,
			Writer = mangaMetadata.Author,
			Penciller = mangaMetadata.Artist,
			Genre = string.Join(",", mangaMetadata.Genres),
			PageCount = pages.Count,
			LanguageISO = "en",
			Pages = pages,
			Notes = "Generated by MangaMagnet v0.0.1 (https://github.com/SimplyMedia/MangaMagnet)",
			ScanInformation = scanlationGroup,
		};

		var wantedVersion = version switch
		{
			ComicInfoVersion.V1 => new Version(1, 0, 0),
			ComicInfoVersion.V2 => new Version(2, 0 , 0),
			ComicInfoVersion.V2_1 => new Version(2, 1, 0),
			_ => throw new ArgumentOutOfRangeException(nameof(version), version, null)
		};

		return comicInfo.GetForVersion(wantedVersion);
	}

	public async Task WriteAsync(XmlComicInfo comicInfo, string outputDirectory, CancellationToken cancellationToken = default)
	{
		var path = Path.Combine(outputDirectory, "ComicInfo.xml");

		var document = await Task.Run(() => _serializer.Serialize(new XmlWriterSettings {Indent = false, OmitXmlDeclaration = true}, comicInfo), cancellationToken);

		await using var fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 4096, true);

		await fileStream.WriteAsync(Encoding.UTF8.GetBytes(document), cancellationToken);
		await fileStream.FlushAsync(cancellationToken);
	}
}
