version: '3.1'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mangamagnet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mangamagnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mangamagnet -d mangamagnet"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    image: mangamagnet-backend
    build:
      context: ./backend
      dockerfile: MangaMagnet.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DOTNET_ConnectionStrings__PostgreSQLConnection: Host=postgres;Port=5432;Database=mangamagnet;Username=mangamagnet;Password=password
      DOTNET_ConnectionStrings__QuartzPostgresSQLConnection: Host=postgres;Port=5432;Database=mangamagnet;Username=mangamagnet;Password=password;Search Path=quartz

  frontend:
    image: mangamagnet-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 43524:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  data: