using System.Text.Json.Serialization;

namespace MangaMagnet.Core.Metadata.Providers.MangaDex.Models.Manga;

public record MangaDexAttributes(
    [property: JsonPropertyName("title")] IReadOnlyDictionary<string, string> Title,
    [property: JsonPropertyName("altTitles")] IReadOnlyList<IReadOnlyDictionary<string, string>> AltTitles,
    [property: JsonPropertyName("description")] MangaDexDescription Description,
    [property: JsonPropertyName("isLocked")] bool? IsLocked,
    [property: JsonPropertyName("links")] MangaDexLinks Links,
    [property: JsonPropertyName("originalLanguage")] string OriginalLanguage,
    [property: JsonPropertyName("lastVolume")] string LastVolume,
    [property: JsonPropertyName("lastChapter")] string LastChapter,
    [property: JsonPropertyName("publicationDemographic")] string PublicationDemographic,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("year")] int? Year,
    [property: JsonPropertyName("contentRating")] string ContentRating,
    [property: JsonPropertyName("tags")] IReadOnlyList<MangaDexTag> Tags,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("chapterNumbersResetOnNewVolume")] bool? ChapterNumbersResetOnNewVolume,
    [property: JsonPropertyName("createdAt")] DateTime? CreatedAt,
    [property: JsonPropertyName("updatedAt")] DateTime? UpdatedAt,
    [property: JsonPropertyName("version")] int? Version,
    [property: JsonPropertyName("availableTranslatedLanguages")] IReadOnlyList<string> AvailableTranslatedLanguages,
    [property: JsonPropertyName("latestUploadedChapter")] string LatestUploadedChapter,
    [property: JsonPropertyName("name")] MangaDexName Name,
    [property: JsonPropertyName("group")] string Group,
    [property: JsonPropertyName("imageUrl")] object ImageUrl,
    [property: JsonPropertyName("biography")] MangaDexBiography Biography,
    [property: JsonPropertyName("twitter")] object Twitter,
    [property: JsonPropertyName("pixiv")] object Pixiv,
    [property: JsonPropertyName("melonBook")] object MelonBook,
    [property: JsonPropertyName("fanBox")] object FanBox,
    [property: JsonPropertyName("booth")] object Booth,
    [property: JsonPropertyName("nicoVideo")] object NicoVideo,
    [property: JsonPropertyName("skeb")] object Skeb,
    [property: JsonPropertyName("fantia")] object Fantia,
    [property: JsonPropertyName("tumblr")] object Tumblr,
    [property: JsonPropertyName("youtube")] object Youtube,
    [property: JsonPropertyName("weibo")] object Weibo,
    [property: JsonPropertyName("naver")] object Naver,
    [property: JsonPropertyName("website")] object Website,
    [property: JsonPropertyName("volume")] string Volume,
    [property: JsonPropertyName("locale")] string Locale
);
