name: Run Backend Tests

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-test.yml
  pull_request:

jobs:
    backend-test:
        name: Backend Tests
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Source code
          uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
        - name: Setup Cache
          uses: actions/cache@v3
          with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: ${{ runner.os }}-nuget-
        - name: Restore dependencies
          run: dotnet restore backend
        - name: Run Build
          run: dotnet build backend --no-restore /p:ContinuousIntegrationBuild=true
        - name: Run Test
          run: dotnet test backend --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        - name: Upload Coverage
          uses: codacy/codacy-coverage-reporter-action@v1
          with:
            api-token: ${{ secrets.CODACY_API_TOKEN }}
            coverage-reports: backend/MangaMagnet.Core.Test/coverage.opencover.xml
